services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/front
    ports:
      - 3000:3000
    container_name: app
    restart: always
    tty: true
    stdin_open: true