services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/front
    ports:
      - 3000:3000
    container_name: app
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true